

services:
  # API Service (builds from Dockerfile.api)
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src # Mount src for hot-reloading
    env_file: ./.env
    command: npm run start:dev:api
    depends_on:
      - redis

  # Worker Service (builds from Dockerfile.worker)
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./src:/usr/src/app/src # Mount src for hot-reloading
    env_file: ./.env
    command: npm run start:dev:worker
    depends_on:
      - redis

  # Database
  

  # Queue
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: